name: Run tests

on:
  push:
    paths:
      - "**.js"
      - "**.json"
      - "**.yaml"
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Restore Dependencies
        uses: npm ci

      - name: Run tests
        uses: npm test
